### ISSUE TITLE
Evidence_check controller

### ISSUE THREAD

**Issue by dotemacs** [hmcts/hwf-staffapp#378]
Find out about it and see why it's a separate controller

**Comment by dotemacs** [comment]
@novotnyjakub is https://github.com/ministryofjustice/fr-staffapp/blob/master/app/controllers/evidence_checks_controller.rb used still in the app? 

Or is it just a left over when the spotchecks were created and then renamed? 

If it isn't used, maybe we can just remove it completely and it's related views & tests?

Thanks

**Comment by novotnyjakub** [comment]
Yes, it is still being used, when an application is selected for spot check, this controller renders the letter which is to be sent to the applicant. 

Originally I thought that it'll be the controller for the whole flow, but we have a different one for that. 

We should discuss it and consolidate, I agree. But we can't remove it just yet.
